pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_PROJECT)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = 'ui-perception'
include ':app'
include ':baseline-pages'
include ':perception-core'
include ':native-plugin'
include ':web-plugin'
include ':ocr-plugin'
include ':small-model-plugin'
