package com.hh.uiperception.core.semantic;

/**
 * Semantic roles shared by the native and web pipelines.
 *
 * Native pipeline: roles are resolved by NativeRoleResolver from Android accessibility nodes.
 * Web pipeline: roles come from the JS DOM serializer (dom-serializer.js), parsed by WebJsonParser.
 *
 * The snapshotName matches the string used in YAML output and JSON wire format.
 */
public enum SemanticRole {

    // ── Native + Web shared ──────────────────────────────
    SCREEN("screen"),
    TOOLBAR("toolbar"),
    TABBAR("tabbar"),
    TAB("tab"),
    LIST("list"),
    GRID("grid"),
    LIST_ITEM("listitem"),
    SCROLL("scroll"),
    CARD("card"),
    SECTION("section"),
    DIALOG("dialog"),
    SHEET("sheet"),
    TEXT("text"),
    IMAGE("image"),
    BUTTON("button"),
    INPUT("input"),
    CHECKBOX("checkbox"),
    RADIO("radio"),
    SWITCH("switch"),
    SLIDER("slider"),
    PICKER("picker"),
    PROGRESS("progress"),
    GENERIC("generic"),
    WEBVIEW("webview"),
    LINK("link"),
    HEADING("heading"),
    NAVIGATION("navigation"),

    // ── Web-specific (HTML ARIA roles) ────────────────────
    // These are generated by dom-serializer.js; NativeRoleResolver does not produce them.
    TEXTBOX("textbox"),
    SEARCHBOX("searchbox"),
    SPINBUTTON("spinbutton"),
    COMBOBOX("combobox"),
    LISTBOX("listbox"),
    TABLE_ROLE("table"),
    ROW("row"),
    CELL("cell"),
    COLUMNHEADER("columnheader"),
    ROWHEADER("rowheader"),
    FORM("form"),
    ARTICLE("article"),
    COMPLEMENTARY("complementary"),   // <aside>
    BLOCKQUOTE("blockquote"),
    CAPTION("caption"),               // <caption> inside <table>
    GROUP("group"),                    // <details>, <optgroup>
    TERM("term"),                      // <dt>
    DEFINITION("definition"),          // <dd>
    SEPARATOR("separator"),            // <hr>
    METER("meter"),                    // <meter>
    OPTION_ROLE("option"),             // <option>
    STATUS("status"),                  // <output>
    PARAGRAPH("paragraph"),            // <p>
    ROWGROUP("rowgroup");              // <thead>, <tbody>, <tfoot>

    private final String snapshotName;

    SemanticRole(String snapshotName) {
        this.snapshotName = snapshotName;
    }

    /** Name used in YAML snapshot output and JSON wire format. */
    public String snapshotName() {
        return snapshotName;
    }
}
