plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
    namespace 'com.hh.uiperception.webplugin'
    compileSdk 34
    buildToolsVersion '34.0.0'

    defaultConfig {
        minSdk 24
        targetSdk 31
        consumerProguardFiles 'consumer-rules.pro'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }

    testOptions {
        unitTests.returnDefaultValues = true
    }
}

dependencies {
    implementation project(':perception-core')
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.json:json:20240303'
}

publishing {
    publications {
        release(MavenPublication) {
            groupId = GROUP
            artifactId = 'web-plugin'
            version = VERSION_NAME

            afterEvaluate {
                from components.release
            }
        }
    }
}
