export class SemanticStates {
  static readonly CLICKABLE: string = 'clickable';
  static readonly CLICKABLE_INFERRED: string = 'clickable-inferred';
  static readonly CLICKABLE_GUESSED: string = 'clickable-guessed';
  static readonly DISABLED: string = 'disabled';
  static readonly CHECKED: string = 'checked';
  static readonly SELECTED: string = 'selected';
  static readonly FOCUSED: string = 'focused';
  static readonly SCROLLABLE: string = 'scrollable';
  static readonly PASSWORD: string = 'password';
}
